name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Write google-services.json
        run: |
          echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > androidApp/google-services.json

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Add Firebase Web Client ID to local.properties
        run: echo "WEB_CLIENT_ID=${{ secrets.FIREBASE_WEB_CLIENT_ID }}" >> local.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: androidApp/build/outputs/apk/debug/androidApp-debug.apk