name: Spotless Check

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  spotless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Spotless Check
        run: ./gradlew spotlessCheck